In [1]:
import numpy as np

In [2]:
s = np.array([33, 65, 50, 45])
s

array([33, 65, 50, 45])

In [3]:
s[2]

50

In [4]:
len(s)

4

In [5]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
a + b

array([15, 23, 14,  8])

In [6]:
a - b

array([ 5, -7, -4, -6])

In [7]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c

array([24. ,  9. , 13.6])

In [8]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

In [9]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

In [10]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [11]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [12]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [13]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [14]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [15]:
import numpy as np
def func_rosen(x):
    r = np.sum(100*(x[1:]-x[:-1]**2)**2 + (1-x[:-1])**2, axis=0)
    return r
 
 
from scipy.optimize import least_squares
x1 = np.array([2.4, 1.5, 2.1, 0.7, 1.1])
res =  least_squares(func_rosen, x1)
print(res.x)

[0.93865173 0.88210868 0.776457   0.60278764 0.36076162]
