In [29]:
import numpy as np

In [41]:
import numpy as np

A = np.array([[8, 6, 11], [7, 5, 9], [6, 10, 6]])
A_inv = np.linalg.inv(A)

# Элемент из первого столбца второй строки
element = A_inv[1, 0]
rounded_element = round(element, 3)

print(rounded_element)


0.375


In [42]:
import numpy as np

# Данные векторы
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

# Создание матрицы системы векторов
A = np.column_stack((v1, v2, v3, v4))

# Нахождение ранга матрицы
rank_A = np.linalg.matrix_rank(A)
rank_A


4

In [43]:
import numpy as np

# Данные векторы
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

# Создание матрицы A
A = np.column_stack((v1, v2, v3, v4))

# Транспонированная матрица A^T
A_T = A.T

# Матрица Грама G = A^T * A
G = np.dot(A_T, A)

# Элемент из четвёртого столбца первой строки
element = G[0, 3]
element


-35

In [44]:
import numpy as np

# Данные векторы
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

# Создание матрицы A
A = np.column_stack((v1, v2, v3, v4))

# Транспонированная матрица A^T
A_T = A.T

# Матрица Грама G = A^T * A
G = np.dot(A_T, A)

# Определитель матрицы Грама G
det_G = np.linalg.det(G)

# Округление до целого числа
rounded_det_G = round(det_G)
rounded_det_G


3716648

In [45]:
import numpy as np

# Векторы системы
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

# Матрица системы векторов (векторы в столбцах)
A = np.column_stack([v1, v2, v3, v4])

# Матрица Грама G = A^T * A
G = np.dot(A.T, A)

# Обратная матрица G
G_inv = np.linalg.inv(G)

# Элемент из первого столбца третьей строки
element = G_inv[2, 0]
print(round(element, 3))


-0.026


In [30]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [31]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [32]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)


A1 inversed:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [33]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

A1 @ A1 inversed=E check:
 [[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]] 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
check OK


In [34]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

A2:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [35]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

rk(A3):
 2


In [36]:
# обратная матрица - вырожденный случай
np.linalg.inv(A2)

In [37]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

A3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

rk(A3):
 2


In [39]:
# обратная матрица - magic
print('A3 inversed:\n',np.linalg.inv(A3))

In [40]:
# обратная матрица - magic
print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

LinAlgError: Singular matrix

In [ ]:
print('det(A1)):\n',np.linalg.det(A1))

In [ ]:
print('det(A2)):\n',np.linalg.det(A2))

In [ ]:
print('det(A3)):\n',np.linalg.det(A3))

In [ ]:
# обратная матрица - неустойчивость
A4=np.array([[1,2,3],[4,5,6],[1,2,3.00005]])
print('A4:\n',A4)
print('rk(A4):\n',np.linalg.matrix_rank(A4))
print('det(A4):\n',np.linalg.det(A4))
print('A4 inverse:\n',np.linalg.inv(A4))

In [ ]:
# обратная матрица - неустойчивость вблизи нулевого определителя
A5=np.array([[1,2,3],[4,5,6],[1,2,3.00000005]])
print('A5:\n',A5)
print('rk(A5):\n',np.linalg.matrix_rank(A5))
print('det(A5):\n',np.linalg.det(A5))
print('A5 inverse:\n',np.linalg.inv(A5))

In [ ]:
# обратимость матрицы Грама линейно независимой системы векторов
v1=np.array([1,2,1])
v2=np.array([1,1,1])
A=np.array([v1,v2]).T
print('A:\n',A)
print('Матрица Грама:\n',A.T@A)

In [ ]:
print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

In [ ]:
print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

In [ ]:
print('Обратная к матрице Грама:\n',np.linalg.inv(A.T@A))