In [1]:
import numpy as np

In [2]:
# как создать матрицу?

In [3]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [4]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# размер матрицы
np.shape(A)

(4, 3)

In [6]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [7]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [8]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [9]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


In [10]:
# создание специальных матриц

In [11]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [16]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [17]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [18]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

In [19]:
A+B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [20]:
B+A

array([[2, 0],
       [0, 6],
       [8, 0]])

In [21]:
A-B

array([[ 0,  2],
       [ 4,  0],
       [ 0, 10]])

In [22]:
2*A

array([[ 2,  2],
       [ 4,  6],
       [ 8, 10]])

In [23]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

In [24]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

array([1, 2, 3])

In [25]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [26]:
x_col.T

array([[1, 2, 3]])

In [27]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


In [28]:
import numpy as np

Husband_Income = np.array([100, 220, 140])
Wife_Income = np.array([150, 200, 130])
Mother_In_Law_Income = np.array([90, 80, 100])

# Создание матрицы доходов и транспонирование
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T

# Получение диагональных элементов
diagonal_elements = np.diagonal(Inc)

# Преобразование диагональных элементов в строку через запятую
answer = ','.join(map(str, diagonal_elements))

print(answer)  # Вывод ответа


100,200,100


In [30]:
import numpy as np

Husband_Consumption = np.array([50, 50, 60])
Wife_Consumption = np.array([100, 80, 140])
Mother_In_Law_Consumption = np.array([100, 20, 140])

# Создание матрицы расходов и транспонирование
Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T

# Получение диагональных элементов
diagonal_elements = np.diagonal(Cons)

# Преобразование диагональных элементов в строку через запятую
answer = ','.join(map(str, diagonal_elements))

print(answer)  # Вывод ответа


50,80,140


In [31]:
import numpy as np

# Дано
Inc = np.array([[100, 150, 90],
                [220, 200, 80],
                [140, 130, 100]])

# Налоговая ставка
tax_rate = 0.13

# Вычисление матрицы доходов после уплаты налогов
Inc_after_tax = Inc * (1 - tax_rate)

# Выбор списка элементов из первой строки матрицы
first_row_elements = Inc_after_tax[0, :]

# Преобразование списка элементов в строку через запятую
answer = ','.join(map(str, first_row_elements))

print(answer)  # Вывод ответа


87.0,130.5,78.3


In [32]:
import numpy as np

# Дано
Inc_after_tax = np.array([[87.0, 130.5, 76.5],
                          [191.4, 174.0, 69.6],
                          [121.8, 113.1, 87.0]])

Cons = np.array([[50, 100, 100],
                 [50, 80, 20],
                 [60, 140, 140]])

# Вычисление матрицы баланса
P = Inc_after_tax - Cons

# Выбор списка элементов из третьей строки матрицы
third_row_elements = P[2, :]

# Преобразование списка элементов в строку через запятую
answer = ','.join(map(str, third_row_elements))

print(answer)  # Вывод ответа


61.8,-26.900000000000006,-53.0
