In [28]:
import numpy as np

In [29]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [30]:
A

array([[ 5,  5, 11],
       [ 6, 10,  7],
       [11, 11,  8]])

In [31]:
B

array([[-1, -1, -2],
       [ 3, -1, -2],
       [-2,  1, -1]])

In [32]:
# Поэлементное умножение
A*B

array([[ -5,  -5, -22],
       [ 18, -10, -14],
       [-22,  11,  -8]])

In [33]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[-12   1 -31]
 [ 10  -9 -39]
 [  6 -14 -52]]


In [34]:
# Матричное умножение
np.dot(A,B)

array([[-12,   1, -31],
       [ 10,  -9, -39],
       [  6, -14, -52]])

In [35]:
# Матричное умножение
A@B

array([[-12,   1, -31],
       [ 10,  -9, -39],
       [  6, -14, -52]])

In [36]:
# Порядок умножения AB != BA
B@A

array([[-33, -37, -34],
       [-13, -17,  10],
       [-15, -11, -23]])

In [37]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 7  8  9  9  7]
 [ 8 10  6  9 10]
 [ 7  6 11  5  7]]
B:
 [[ 0  3]
 [ 1  3]
 [ 0  2]
 [-2  3]
 [ 3 -2]]


In [38]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[11, 76],
       [22, 73],
       [17, 62]])

In [39]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

In [ ]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

In [ ]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

In [ ]:
b@A

In [ ]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

In [ ]:
# матрица Грама ортогональной системы векторов
A@A.T

In [ ]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

In [ ]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

In [ ]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

In [ ]:
import numpy as np

# Заданные матрица A и вектор x
A = np.array([[5, -1, 3, 1, 2],
              [-2, 8, 5, -1, 1]])
x = np.array([1, 2, 3, 4, 5])

# Умножение матрицы A на вектор x
result_vector = np.dot(A, x)

# Вывод результата в виде координат через запятую
print(','.join(map(str, result_vector)))


26,30


In [ ]:
import numpy as np

# Заданные матрицы A и B
A = np.array([[1, 9, 8, 5],
              [3, 6, 3, 2],
              [3, 3, 3, 3],
              [0, 2, 5, 9],
              [4, 4, 1, 2]])

B = np.array([[1, -1, 0, 1, 1],
              [-2, 0, 2, -1, 1]])

# Умножение матрицы B на матрицу A
result_matrix = np.dot(B, A)

# Извлечение элемента в четвертом столбце первой строки результата
element_14 = result_matrix[0, 3]

# Вывод результата (элемента в четвертом столбце первой строки)
print(int(element_14))  # Преобразуем к целому числу и выводим



14


In [ ]:
import numpy as np

# Заданные векторы
x = np.array([1, 2, 1, 0, 4])
y = np.array([2, 1, -1, 1, 0])
z = np.array([-1, 1, -1, 0, 0])

# Составляем матрицу A, где каждый вектор - строка матрицы
A = np.array([x, y, z])

print("Матрица A:")
print(A)


Матрица A:
[[ 1  2  1  0  4]
 [ 2  1 -1  1  0]
 [-1  1 -1  0  0]]


In [ ]:
# Находим матрицу Грама G (скалярные произведения столбцов матрицы A)
G = np.dot(A.T, A)

print("Матрица Грама G:")
print(G)


Матрица Грама G:
[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


In [ ]:
import pandas as pd
import numpy as np

# Заданные данные в виде DataFrame
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания': [12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка': [15, 25, 30, 14, 25, 17, 25, 31],
    'Уход': [10, 6, 4, 5, 18, 12, 20, 28]
}, index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя', 'Юра'])

Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания': [1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка': [0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход': [1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
}, index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя', 'Юра'])

# Вектор комиссий
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

# Вычисление дохода салона для каждого стилиста с учетом комиссий
# Умножаем стоимость услуги на количество услуг и  комиссию
revenue = (Price_DF * Count_DF * com).sum(axis=1)

# Вывод вектора дохода салона
print("Вектор дохода салона по стилистам:")
print(revenue)


Вектор дохода салона по стилистам:
Аня      11.30
Борис    15.22
Вика     11.90
Галя     20.60
Дима     41.90
Егор     21.20
Женя     11.49
Юра      38.25
dtype: float64


In [ ]:
# Вычисление дохода для каждого стилиста с учетом комиссий
# Умножаем стоимость услуги на количество услуг и (1 - комиссия)
revenue = (Price_DF * Count_DF * (1 - com)).sum(axis=1)

# Вывод вектора дохода стилиста
print("Вектор дохода стилистов с учетом комиссий:")
print(revenue)

Вектор дохода стилистов с учетом комиссий:
Аня       50.20
Борис     74.88
Вика      59.10
Галя      67.80
Дима     166.60
Егор     113.80
Женя      66.21
Юра      157.75
dtype: float64
